<<<<<<< HEAD
---
title: "Model Building"
author: Gannon and Kent
output: html_document
---

# Steps

1. Load ISAF Data
2. Descriptive statistics
3. Models
  3a. Why contribute amount of troops?
  3b. Does it pay off?

# Data loading

```{R}
isaf <- rio::import('../data/iiss_afghan_complete.rds')
## Remove afghanistan because it is not a realistic self-contributor
## Remove US because paper is about relations with the US
isaf <- dplyr::filter(isaf, stateabb != "AFG" & stateabb != "USA")
```

# Key predictor -- diff between ideal point and alliance depth

+ Standardize depth to be between 0 and 1. 

```{R}
## Make all values positive
isaf$depth <- isaf$depth + abs(summary(isaf$depth)[1]) 
## Divide by max to make between 0 and 1
isaf$depth <- isaf$depth/summary(isaf$depth)[6]
```

+ Create potential gain variable:

```{R}
isaf$pot_gain <- isaf$pctagreeus - isaf$depth
```

+ US ally variable

```{R}
## Create alliance (not including non-aggression pact) variable
isaf$us_ally <- ifelse(
  !is.na(isaf$depth), ## if there is a depth score
  1, 0 ## 0 if no depth score (no alliance), 1 if there is a depth score
)
```

+ Exploratory Models

```{R}
m1 <- glm(troops_afghan_ratio ~ pot_gain + dem, 
  data = dplyr::filter(isaf, us_ally == 1)) 
  ## unnecessary to filter by us ally, because gets dropped, but I want 
  ## to keep track of the data partitions
summary(m1)

m2 <- glm(troops_afghan_ratio ~ pctagreeus,
  data = dplyr::filter(isaf, us_ally == 0))
summary(m2)

## Something is up with Iceland... Why is it coded as zero troops?
## Remove for now
m3 <- glm(troops_afghan_ratio ~ pctagreeus,
  data = dplyr::filter(isaf, ccode != 395))
summary(m3)

## Need to drop Iceland
m4 <- glm(troops_afghan_ratio ~ pot_gain ,
  data = dplyr::filter(test, ccode != 395))
summary(m4)

## Israel??
```

+ Idea: All models have a positive coefficient. Show that the first one -- potential gain -- has the best fit with cross-validation. 

## Descriptive statistics

+ Look at which observations actually contribute the most:

```{R}
contributions <- dplyr::select(dplyr::filter(isaf, country != "Iceland"), 
  c(year, country, troops_afghan_ratio))

## Biggest contributors
contributions[order(-contributions$troops_afghan_ratio),][1:100,]

## Start of conflict
contributions2 <- dplyr::select(dplyr::filter(isaf, 
  country != "Iceland" & year == 2001), 
  c(year, country, troops_afghan_ratio))

contributions2[order(-contributions2$troops_afghan_ratio),][1:20,]
```

+ What happens if we just have all countries without alliances be coded as zero in depth:

```{R}
colnames(isaf)

test <- isaf
for(i in 1:nrow(test)){
  if(test[i,27] == 0){
    test[i,25] <- 0
  }
}

test$pot_gain <- test$pctagreeus - test$depth

ggplot(dplyr::filter(test, country != "Iceland"), aes(x = pot_gain, y = troops_afghan_ratio)) + 
  geom_point() + 
  geom_text(aes(label=stateabb), hjust=0, vjust=1, size = 2) +
  geom_smooth(method = "glm") +
  theme_bw()

contributions3 <- dplyr::select(dplyr::filter(test, country != "Iceland"), 
  c(year, country, troops_afghan_ratio))

## Biggest contributors
contributions3[order(-contributions3$troops_afghan_ratio),][1:100,]

pot_gain <- dplyr::select(dplyr::filter(test, country != "Iceland"), 
  c(year, country, pot_gain))

pot_gain[order(-pot_gain$pot_gain),][1:100,]
```

+ If we include all non-allies as zero depth with US, then Israel has the most to gain because it votes in tandem with the US, but no troop contributions.
  + Also, Israel lacks a formal military alliance but has intense US military cooperation and aid, so doesn't need to signal.
    + Israel not in graph:

```{R}
ggplot(dplyr::filter(test, country != "Iceland" & country != "Israel"), 
  aes(x = pot_gain, y = troops_afghan_ratio)) + 
  geom_point() + 
  geom_text(aes(label=stateabb), hjust=0, vjust=1, size = 2) +
  geom_smooth() +
  theme_bw()
```

+ PLot also reveals that the United Kingdom's ideological baseline is so close with the US that the degree of military cooperation realistically still has room to grow.

+ So if we look at the entire dataset, UK is first which follows closeness of alliance hypothesis. But then we have Georgia, Denmark, Netherlands, Canada, Georgia, Latvia, Estonia, New Zealand, etc. 
  + For other contributors, the big ones are those with room to gain. 

```{R}
pot_gain <- dplyr::select(dplyr::filter(isaf, country != "Iceland"), 
  c(year, country, pot_gain))

## Biggest contributors
contributions[order(-contributions$troops_afghan_ratio),][1:100,]
```

+ First, let's see how our DV varies by our predictors:

+ Alliance with the US, faceted by voting similarity with the United States.


```{R}
## need to import ggplot, gets messy as ggplot2::ggplot()
library(ggplot2)

## Remove Iceland because of strange infinity values
ggplot(dplyr::filter(isaf, country != "Iceland"), aes(x = pot_gain, y = troops_afghan_ratio)) + 
  geom_point() + 
  geom_text(aes(label=stateabb), hjust=0, vjust=1, size = 2) +
  geom_smooth() +
  theme_bw()

## What about percent shared vote?
ggplot(dplyr::filter(isaf, country != "Iceland"), 
  aes(x = idealpoint, y = troops_afghan_ratio)) + 
  geom_point() + 
  geom_text(aes(label=stateabb), hjust=0, vjust=1, size = 2) +
  geom_smooth() +
  theme_bw()


```


```{R}
## points cluster by country, so fairly noisy
ggplot(isaf, aes(x = pot_gain, y = troops_afghan_ratio)) + 
  geom_point() +
    geom_text(aes(label=stateabb),hjust=0, vjust=0, size = 2)

## New dataset which averages across contributions and predictors
countries <- unique(isaf$stateabb)
isaf_avg <- dplyr::tibble(country = as.character(),
                      avg_contr = as.numeric(),
                      degree = as.integer(),
                      ideal_point = as.numeric(),
                      eigen = as.numeric(),
                      sequiv = as.integer())

## Loop to fill in average country contributions
for(i in 1:length(countries)){
  abb <- countries[i]
  ## subset on country
  temp <- dplyr::filter(isaf, stateabb == abb)
  ## store country name
  isaf_avg[i,1] <- as.character(abb)
  ## average contr
  isaf_avg[i,2] <- sum(temp$troops_afghan_ratio)/nrow(temp)
  ## average degree
  isaf_avg[i,3] <- sum(temp$degree)/nrow(temp)
  ## average ideal_point
  isaf_avg[i,4] <- sum(temp$abs_ideal_diff)/nrow(temp)
  ## average eigenvector centrality
  isaf_avg[i,5] <- sum(temp$eigen)/nrow(temp)
  ## average structural equivalence
  isaf_avg[i,6] <- sum(temp$sequiv)/nrow(temp)
}


## Plot with Canada
contr_plot_can <- ggplot(isaf_avg,
              aes(x = sequiv, y = avg_contr, label = country)) +
      geom_point(size = 2) +
      ggrepel::geom_text_repel(size = 3.5,
                      segment.color = 'transparent',
                      data = subset(isaf_avg, avg_contr > 0)) +
      geom_smooth(level = 0.95) + theme_classic() +
      labs(title = "Average Troop Contributions by Structural Equivalence with the U.S.",
          x = "Alliance Network Structural Equivalence with the U.S.",
          y = "Average Ratio of Troops Contributed Relative to Total Troops") +
      theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/contributions_canada.png')


## Plot without Canada
## Remove Canada for curvilinear plot, but not analysis
isaf_avg_sub <- dplyr::filter(isaf_avg, country != "CAN")

## Now our curvilinear plot without Canada
## Remove non-contributor labels to avoid mess
contr_plot <- ggplot(isaf_avg_sub,
              aes(x = sequiv, y = avg_contr, label = country)) +
      geom_point(size = 2) +
      ggrepel::geom_text_repel(size = 3.5,
                      segment.color = 'transparent',
                      data = subset(isaf_avg_sub, avg_contr > 0)) +
      geom_smooth(level = 0.95) + theme_classic() +
      labs(title = "Average Troop Contributions by Structural Equivalence with the U.S.",
          x = "Alliance Network Structural Equivalence with the U.S.",
          y = "Average Ratio of Troops Contributed Relative to Total Troops") +
      theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/contributions.png')


side_plot <- cowplot::plot_grid(contr_plot, contr_plot_can,
              width = 8, height = 5)

ggsave('paper/figures/contributions_side.png', width = 10, height = 7)
```

## Network visual

```{R}
load("data/alliance_networks.RData")
require(network)
isaf_alliance_nets <- x

## Troop data
isaf2 <- rio::import('data/iiss_afghan_complete.rds')
## Remove afghanistan because it is not a realistic self-contributor
se <- sna::sedist(isaf_alliance_nets[[2]], method = "correlation")
## contributions
isaf02 <- dplyr::filter(isaf2, year == 2002)
isaf02 <- dplyr::select(isaf02, c(stateabb, troops_afghan_ratio))
countries <- network::get.vertex.attribute(isaf_alliance_nets[[2]],
              "vertex.names")
countries <- data.frame(countries)
colnames(countries) <- c("stateabb")
troop_contr <- dplyr::left_join(countries, isaf02)
set.vertex.attribute(isaf_alliance_nets[[2]], "contributions",
                    troop_contr$troops_afghan_ratio)
contributions <- get.vertex.attribute(isaf_alliance_nets[[2]], "contributions")

plot(isaf_alliance_nets[[2]], displaylabels = TRUE,
    label=network.vertex.names(isaf_alliance_nets[[1]]),
    displayisolates = TRUE, label.cex = 0.75,
    #vertex.cex=200*contributions,label.cex=0.75,
    edge.col=rgb(150,150,150,100,maxColorValue=255),
    label.pos=5,vertex.col="lightblue")

plot(isaf_alliance_nets[[1]])
## https://www.jessesadler.com/post/network-analysis-with-r/

library(tidygraph)
library(ggraph)

allynet <- intergraph::asIgraph(isaf_alliance_nets[[2]])
ally_igraph_tidy <- as_tbl_graph(allynet)
## Not a bad idea to the extent that it gives us control over
## size and color based on variables...
## We can build in casualties and centrality here...
ggraph(ally_igraph_tidy) +
    geom_edge_link() +
    geom_node_point() +
    geom_node_text(aes(label = vertex.names), repel = TRUE) +
    labs() +
    theme_graph()
```

# Model Estimation

A polynomial equation does not fit the data well and GAMs introduce interpretation barriers that may not be necessary. An easy fix seems to be fitting two separate models, representing two steps:
1) who contributes at all?
2) among contributors, what predicts the log of contributions?

## Who contributes at all?

This relationship is not hypothesized to be non-linear. That applies instead to the amount that a state contributes. Here ideological distance is the best predictor of contributions.

```{R}
## Who contributes at all?
isaf$contributor <- 0
for(i in 1:nrow(isaf)){
  if(isaf[i,6] > 0){ ## if troops provided > 0
    isaf[i,44] <- 1 ## make contributor 1
  }
}
```


```{R}
## plot contributor vs non contributor

## Network only
model1 <- glm(contributor ~ sequiv + abs_ideal_diff,
              family = binomial(link = "logit"), data = isaf)
summary(model1)

## Network FE
model2 <- plm::plm(contributor ~ sequiv + abs_ideal_diff,
              family = binomial(link = "logit"),
              index = c("year", "country"), data = isaf)
summary(model2)


## Network and controls
model3 <- glm(contributor ~ sequiv + abs_ideal_diff + dem + distance,
              family = binomial(link = "logit"), data = isaf)
summary(model3)

## Network and controls, FE
model4 <- plm::plm(contributor ~ sequiv + abs_ideal_diff +
                    dem + distance,
              family = binomial(link = "logit"),
              index = c("year", "country"), data = isaf)
summary(model4)


library(dotwhisker)
library(dplyr)

## Coefficient plot
dwplot(list(model1, model2, model3, model4), dodge_size = 0.2) %>%
  relabel_predictors(c(sequiv = "Structural Equivalence",
                        abs_ideal_diff = "Ideal Point Distance",
                        degree = "Network Degrees",
                        dem = "Democracy",
                        distance = "Distance")) +
  theme_classic() +
  xlab("Coefficient Estimate") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  scale_colour_hue(name = "Models",
                    labels = c("Network Only", "Network Only, FE", "Full Model","Full Model, FE")) +
  labs(title = "Logistic Regression Estimates of Decision to Commit Troops") +
  theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/logit_coef.png')

## Predicted probability of committing troops by absolute point ideal diff
## Note ideology predicts whether or not to contribute best.
## Much less uncertainty than sequiv, which visuals show.

## https://stackoverflow.com/questions/39783358/ggplot2-and-glm-plot-a-predicted-probability
logit_plot <- ggplot(isaf, aes(x = abs_ideal_diff, y = contributor)) +
    geom_point() +
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE) +
  labs(x ="Distance from U.S. Ideal Point",
  y ="Probability of Committing Troops",
  title ="Probability of Committing Troops by Ideological Distance from the U.S.") +
  theme_classic() +
  theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/logit.png')

```

## How much do they contribute?

```{R}
## Model 2: How many troops do contributors provide?
isaf_contributors <- dplyr::filter(isaf, troops_afghan_total > 0)

## Without Canada
isaf_con_no_canada <- dplyr::filter(isaf_contributors, country != "Canada")
```


Including a squared term can tell you if the forced-polynomial term is reasonably non-zero. But it can't tell you if the polynomial relationship that we have chosen is the best way to describe the relationship. So we use a gam and find a similar story.

```{R}
model5 <- glm(troops_afghan_ratio ~ sequiv + abs_ideal_diff,
              data = isaf_contributors)
broom::tidy(model5)

model6 <- plm::plm(troops_afghan_ratio ~ poly(sequiv, 2) + abs_ideal_diff,
                index = c("year", "country"), data = isaf_contributors)
broom::tidy(model6)

model7 <- glm(troops_afghan_ratio ~ sequiv + abs_ideal_diff +
              dem + distance,
              data = isaf_contributors)
broom::tidy(model7)

## No difference
model8 <- plm::plm(troops_afghan_ratio ~ sequiv + abs_ideal_diff +
              dem + distance,
                  index = c("year", "country"), data = isaf_contributors)
broom::tidy(model8)

## Structural equivalence polynomial is robust here...

dwplot(list(model5, model6, model7, model8), dodge_size = 0.2) %>%
  relabel_predictors(c(sequiv = "Structural Equivalence",
                        abs_ideal_diff = "Ideal Point Distance",
                        dem = "Democracy",
                        distance = "Distance")) +
  theme_classic() +
  xlab("Coefficient Estimate") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  scale_colour_hue(name = "Models",
                    labels = c("Network Only", "Network Only, FE", "Full Model", "Full Model, FE")) +
  labs(title = "Linear Regression Estimates of Amount of Troops Committed") +
    theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))


ggsave('paper/figures/linear_coef.png')
```

- GAM -- structural equivalence. Should we include other variables?
For differentiating post-treatment bias and multicollinearity: https://stats.stackexchange.com/questions/163174/why-is-post-treatment-bias-a-bias-and-not-just-multicollinearity

```{R}
## No Canada
gam1 <- mgcv::gam(troops_afghan_ratio ~ s(sequiv), data = isaf_con_no_canada)
## pdf("paper/figures/no_can_gam.pdf")
plot(gam1, se = TRUE)
plot1 <- gratia:: draw(gam1)
plot1 + theme_classic()
## dev.off()
summary(gam1)




## With Canada
gam2 <- gam(troops_afghan_ratio ~ s(sequiv), data = isaf_contributors)
pdf("paper/figures/can_gam.pdf")
can_plot <- plot(gam2)
dev.off()
summary(gam2)

## Don't want degree b/c correlated with sequiv w/US, and isn't part of story.
## Our story is not how many alliance ties a state has, but how closely it is tied to the US. This is captured by how similar its network is to the US.
## Ideological distance is cool, but risks post-treatment bias. That means that a state has similar preferences as the US. Cor is -0.39467. So ideological distance shrinks when more structurally equivalent. But again,
## Why to not include degree: Multicollinearity -- so hard to interpret coefficients
## cor(isaf_contributors$sequiv, isaf_contributors$degree)
## [1] 0.8911621

# Don't expect that ideological agreement predicts non-linear relationship.
# The story is about gains in additional allies.
# If preferences align, then expect to care about the conflict and give more.
gam3 <- gam(troops_afghan_ratio ~ s(sequiv) + abs_ideal_diff,
            data = isaf_con_no_canada)
plot(gam3, se = TRUE)
summary(gam3)

gam4 <- gam(troops_afghan_ratio ~ s(sequiv) + abs_ideal_diff,
            data = isaf_contributors)
plot(gam4)
summary(gam4)
```
=======
---
title: "Model Building"
author: Gannon and Kent
output: html_document
---

# Steps

1. Load ISAF Data
2. Descriptive statistics
3. Models
  3a. Why contribute amount of troops?
  3b. Does it pay off?

# Data loading

```{R}
isaf <- rio::import('../data/iiss_afghan_complete.rds')
## Remove afghanistan because it is not a realistic self-contributor
## Remove US because paper is about relations with the US
isaf <- dplyr::filter(isaf, stateabb != "AFG" & stateabb != "USA")
## Only focus on years 2001-2005
##isaf <- dplyr::filter(isaf, year <= 2005)
## Somehow still duplicates, fix later...
## isaf <- isaf[!duplicated(isaf[c("ccode", "year")]),]
```

# Key predictor -- diff between ideal point and alliance depth

+ Standardize depth to be between 0 and 1. 

```{R}
## Make all values positive
isaf$depth <- isaf$depth + abs(summary(isaf$depth)[1]) 
## Divide by max to make between 0 and 1
isaf$depth <- isaf$depth/summary(isaf$depth)[6]
```

+ Create potential gain variable:

```{R}
isaf$pot_gain <- isaf$pctagreeus - isaf$depth

m1 <- glm(troops_afghan_ratio ~ pot_gain + dem, 
  data = dplyr::filter(isaf, us_ally == 1))
summary(m1)

m2 <- glm(troops_afghan_ratio ~ pctagreeus,
  data = dplyr::filter(isaf, us_ally == 0))
summary(m2)

## Something is up with Iceland... Why is it coded as zero troops?
## Remove for now
m3 <- glm(troops_afghan_ratio ~ pctagreeus,
  data = dplyr::filter(isaf, ccode != 395))
summary(m3)
```

+ Idea: All models have a positive coefficient. Show that the first one -- potential gain -- has the best fit with cross-validation. 

## Descriptive statistics

+ First, let's see how our DV varies by our predictors:

+ Alliance with the US, faceted by voting similarity with the United States.

```{R}
## need to import ggplot, gets messy as ggplot2::ggplot()
library(ggplot2)

## Create alliance (not including non-aggression pact) variable
isaf$us_ally <- ifelse(
  !is.na(isaf$depth), ## if there is a depth score
  1, 0 ## 0 if no depth score (no alliance), 1 if there is a depth score
)


ggplot(isaf, aes(x = pctagreeus, y = troops_afghan_ratio)) + 
  geom_point() + 
  geom_smooth(method = "glm") + 
  facet_grid(rows = vars(us_ally)) + 
  theme_bw()

ggplot(isaf, aes(x = pot_gain, y = troops_afghan_ratio)) + 
  geom_point() + 
  geom_smooth(method = "glm")
```


```{R}
## points cluster by country, so fairly noisy
ggplot(isaf, aes(x = pot_gain, y = troops_afghan_ratio)) + 
  geom_point() +
    geom_text(aes(label=stateabb),hjust=0, vjust=0, size = 2)

## New dataset which averages across contributions and predictors
countries <- unique(isaf$stateabb)
isaf_avg <- dplyr::tibble(country = as.character(),
                      avg_contr = as.numeric(),
                      degree = as.integer(),
                      ideal_point = as.numeric(),
                      eigen = as.numeric(),
                      sequiv = as.integer())

## Loop to fill in average country contributions
for(i in 1:length(countries)){
  abb <- countries[i]
  ## subset on country
  temp <- dplyr::filter(isaf, stateabb == abb)
  ## store country name
  isaf_avg[i,1] <- as.character(abb)
  ## average contr
  isaf_avg[i,2] <- sum(temp$troops_afghan_ratio)/nrow(temp)
  ## average degree
  isaf_avg[i,3] <- sum(temp$degree)/nrow(temp)
  ## average ideal_point
  isaf_avg[i,4] <- sum(temp$abs_ideal_diff)/nrow(temp)
  ## average eigenvector centrality
  isaf_avg[i,5] <- sum(temp$eigen)/nrow(temp)
  ## average structural equivalence
  isaf_avg[i,6] <- sum(temp$sequiv)/nrow(temp)
}


## Plot with Canada
contr_plot_can <- ggplot(isaf_avg,
              aes(x = sequiv, y = avg_contr, label = country)) +
      geom_point(size = 2) +
      ggrepel::geom_text_repel(size = 3.5,
                      segment.color = 'transparent',
                      data = subset(isaf_avg, avg_contr > 0)) +
      geom_smooth(level = 0.95) + theme_classic() +
      labs(title = "Average Troop Contributions by Structural Equivalence with the U.S.",
          x = "Alliance Network Structural Equivalence with the U.S.",
          y = "Average Ratio of Troops Contributed Relative to Total Troops") +
      theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/contributions_canada.png')


## Plot without Canada
## Remove Canada for curvilinear plot, but not analysis
isaf_avg_sub <- dplyr::filter(isaf_avg, country != "CAN")

## Now our curvilinear plot without Canada
## Remove non-contributor labels to avoid mess
contr_plot <- ggplot(isaf_avg_sub,
              aes(x = sequiv, y = avg_contr, label = country)) +
      geom_point(size = 2) +
      ggrepel::geom_text_repel(size = 3.5,
                      segment.color = 'transparent',
                      data = subset(isaf_avg_sub, avg_contr > 0)) +
      geom_smooth(level = 0.95) + theme_classic() +
      labs(title = "Average Troop Contributions by Structural Equivalence with the U.S.",
          x = "Alliance Network Structural Equivalence with the U.S.",
          y = "Average Ratio of Troops Contributed Relative to Total Troops") +
      theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/contributions.png')


side_plot <- cowplot::plot_grid(contr_plot, contr_plot_can,
              width = 8, height = 5)

ggsave('paper/figures/contributions_side.png', width = 10, height = 7)
```

## Network visual

```{R}
load("data/alliance_networks.RData")
require(network)
isaf_alliance_nets <- x

## Troop data
isaf2 <- rio::import('data/iiss_afghan_complete.rds')
## Remove afghanistan because it is not a realistic self-contributor
se <- sna::sedist(isaf_alliance_nets[[2]], method = "correlation")
## contributions
isaf02 <- dplyr::filter(isaf2, year == 2002)
isaf02 <- dplyr::select(isaf02, c(stateabb, troops_afghan_ratio))
countries <- network::get.vertex.attribute(isaf_alliance_nets[[2]],
              "vertex.names")
countries <- data.frame(countries)
colnames(countries) <- c("stateabb")
troop_contr <- dplyr::left_join(countries, isaf02)
set.vertex.attribute(isaf_alliance_nets[[2]], "contributions",
                    troop_contr$troops_afghan_ratio)
contributions <- get.vertex.attribute(isaf_alliance_nets[[2]], "contributions")

plot(isaf_alliance_nets[[2]], displaylabels = TRUE,
    label=network.vertex.names(isaf_alliance_nets[[1]]),
    displayisolates = TRUE, label.cex = 0.75,
    #vertex.cex=200*contributions,label.cex=0.75,
    edge.col=rgb(150,150,150,100,maxColorValue=255),
    label.pos=5,vertex.col="lightblue")

plot(isaf_alliance_nets[[1]])
## https://www.jessesadler.com/post/network-analysis-with-r/

library(tidygraph)
library(ggraph)

allynet <- intergraph::asIgraph(isaf_alliance_nets[[2]])
ally_igraph_tidy <- as_tbl_graph(allynet)
## Not a bad idea to the extent that it gives us control over
## size and color based on variables...
## We can build in casualties and centrality here...
ggraph(ally_igraph_tidy) +
    geom_edge_link() +
    geom_node_point() +
    geom_node_text(aes(label = vertex.names), repel = TRUE) +
    labs() +
    theme_graph()
```

# Model Estimation

A polynomial equation does not fit the data well and GAMs introduce interpretation barriers that may not be necessary. An easy fix seems to be fitting two separate models, representing two steps:
1) who contributes at all?
2) among contributors, what predicts the log of contributions?

## Who contributes at all?

This relationship is not hypothesized to be non-linear. That applies instead to the amount that a state contributes. Here ideological distance is the best predictor of contributions.

```{R}
## Who contributes at all?
isaf$contributor <- 0
for(i in 1:nrow(isaf)){
  if(isaf[i,6] > 0){ ## if troops provided > 0
    isaf[i,44] <- 1 ## make contributor 1
  }
}
```


```{R}
## plot contributor vs non contributor

## Network only
model1 <- glm(contributor ~ sequiv + abs_ideal_diff,
              family = binomial(link = "logit"), data = isaf)
summary(model1)

## Network FE
model2 <- plm::plm(contributor ~ sequiv + abs_ideal_diff,
              family = binomial(link = "logit"),
              index = c("year", "country"), data = isaf)
summary(model2)


## Network and controls
model3 <- glm(contributor ~ sequiv + abs_ideal_diff + dem + distance,
              family = binomial(link = "logit"), data = isaf)
summary(model3)

## Network and controls, FE
model4 <- plm::plm(contributor ~ sequiv + abs_ideal_diff +
                    dem + distance,
              family = binomial(link = "logit"),
              index = c("year", "country"), data = isaf)
summary(model4)


library(dotwhisker)
library(dplyr)

## Coefficient plot
dwplot(list(model1, model2, model3, model4), dodge_size = 0.2) %>%
  relabel_predictors(c(sequiv = "Structural Equivalence",
                        abs_ideal_diff = "Ideal Point Distance",
                        degree = "Network Degrees",
                        dem = "Democracy",
                        distance = "Distance")) +
  theme_classic() +
  xlab("Coefficient Estimate") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  scale_colour_hue(name = "Models",
                    labels = c("Network Only", "Network Only, FE", "Full Model","Full Model, FE")) +
  labs(title = "Logistic Regression Estimates of Decision to Commit Troops") +
  theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/logit_coef.png')

## Predicted probability of committing troops by absolute point ideal diff
## Note ideology predicts whether or not to contribute best.
## Much less uncertainty than sequiv, which visuals show.

## https://stackoverflow.com/questions/39783358/ggplot2-and-glm-plot-a-predicted-probability
logit_plot <- ggplot(isaf, aes(x = abs_ideal_diff, y = contributor)) +
    geom_point() +
  stat_smooth(method="glm", method.args=list(family="binomial"), se=TRUE) +
  labs(x ="Distance from U.S. Ideal Point",
  y ="Probability of Committing Troops",
  title ="Probability of Committing Troops by Ideological Distance from the U.S.") +
  theme_classic() +
  theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))

ggsave('paper/figures/logit.png')

```

## How much do they contribute?

```{R}
## Model 2: How many troops do contributors provide?
isaf_contributors <- dplyr::filter(isaf, troops_afghan_total > 0)

## Without Canada
isaf_con_no_canada <- dplyr::filter(isaf_contributors, country != "Canada")
```


Including a squared term can tell you if the forced-polynomial term is reasonably non-zero. But it can't tell you if the polynomial relationship that we have chosen is the best way to describe the relationship. So we use a gam and find a similar story.

```{R}
model5 <- glm(troops_afghan_ratio ~ sequiv + abs_ideal_diff,
              data = isaf_contributors)
broom::tidy(model5)

model6 <- plm::plm(troops_afghan_ratio ~ poly(sequiv, 2) + abs_ideal_diff,
                index = c("year", "country"), data = isaf_contributors)
broom::tidy(model6)

model7 <- glm(troops_afghan_ratio ~ sequiv + abs_ideal_diff +
              dem + distance,
              data = isaf_contributors)
broom::tidy(model7)

## No difference
model8 <- plm::plm(troops_afghan_ratio ~ sequiv + abs_ideal_diff +
              dem + distance,
                  index = c("year", "country"), data = isaf_contributors)
broom::tidy(model8)

## Structural equivalence polynomial is robust here...

dwplot(list(model5, model6, model7, model8), dodge_size = 0.2) %>%
  relabel_predictors(c(sequiv = "Structural Equivalence",
                        abs_ideal_diff = "Ideal Point Distance",
                        dem = "Democracy",
                        distance = "Distance")) +
  theme_classic() +
  xlab("Coefficient Estimate") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  scale_colour_hue(name = "Models",
                    labels = c("Network Only", "Network Only, FE", "Full Model", "Full Model, FE")) +
  labs(title = "Linear Regression Estimates of Amount of Troops Committed") +
    theme(text = element_text(size = 13),
      plot.title = element_text(size = 13))


ggsave('paper/figures/linear_coef.png')
```

- GAM -- structural equivalence. Should we include other variables?
For differentiating post-treatment bias and multicollinearity: https://stats.stackexchange.com/questions/163174/why-is-post-treatment-bias-a-bias-and-not-just-multicollinearity

```{R}
## No Canada
gam1 <- mgcv::gam(troops_afghan_ratio ~ s(sequiv), data = isaf_con_no_canada)
## pdf("paper/figures/no_can_gam.pdf")
plot(gam1, se = TRUE)
plot1 <- gratia:: draw(gam1)
plot1 + theme_classic()
## dev.off()
summary(gam1)




## With Canada
gam2 <- gam(troops_afghan_ratio ~ s(sequiv), data = isaf_contributors)
pdf("paper/figures/can_gam.pdf")
can_plot <- plot(gam2)
dev.off()
summary(gam2)

## Don't want degree b/c correlated with sequiv w/US, and isn't part of story.
## Our story is not how many alliance ties a state has, but how closely it is tied to the US. This is captured by how similar its network is to the US.
## Ideological distance is cool, but risks post-treatment bias. That means that a state has similar preferences as the US. Cor is -0.39467. So ideological distance shrinks when more structurally equivalent. But again,
## Why to not include degree: Multicollinearity -- so hard to interpret coefficients
## cor(isaf_contributors$sequiv, isaf_contributors$degree)
## [1] 0.8911621

# Don't expect that ideological agreement predicts non-linear relationship.
# The story is about gains in additional allies.
# If preferences align, then expect to care about the conflict and give more.
gam3 <- gam(troops_afghan_ratio ~ s(sequiv) + abs_ideal_diff,
            data = isaf_con_no_canada)
plot(gam3, se = TRUE)
summary(gam3)

gam4 <- gam(troops_afghan_ratio ~ s(sequiv) + abs_ideal_diff,
            data = isaf_contributors)
plot(gam4)
summary(gam4)
```
>>>>>>> 7e94fd125f7563094e9ef49b5a508fd5e25b8e3b
